/**
 * Codegen for src/snap-registry.ts.
 *
 * Scans src/snaps/ for snap directories (each one expected to contain an
 * index.ts that exports a default Hono sub-app) and writes a static
 * registry that the main entry imports. Static imports are mandatory
 * because the project deploys to Vercel's Hono framework preset which
 * uses the Edge runtime — Edge has no filesystem and bundlers cannot
 * resolve runtime fs.readdirSync calls.
 *
 * Run automatically before `npm run build` and `npm run dev` via the
 * "prebuild" / "predev" scripts in package.json. The generated file is
 * committed to git so Vercel deploys what's on disk without needing to
 * run codegen itself.
 */
import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dir, "..");
const snapsDir = join(projectRoot, "src", "snaps");
const registryFile = join(projectRoot, "src", "snap-registry.ts");

function toIdentifier(name: string): string {
  // kebab-case → camelCase, prefixed with `snap_` to avoid keyword clashes
  const camel = name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  return `snap_${camel.replace(/[^a-zA-Z0-9_$]/g, "_")}`;
}

function main(): void {
  if (!existsSync(snapsDir)) {
    // No snaps yet — write an empty registry so the build still works.
    const empty = [
      "// AUTO-GENERATED by scripts/generate-registry.ts. Do not edit by hand.",
      "// Re-run via `npm run generate` (or `npm run build` which calls it).",
      "",
      'import type { Hono } from "hono";',
      "",
      "export const snaps: Record<string, Hono> = {};",
      "",
    ];
    writeFileSync(registryFile, empty.join("\n"));
    // eslint-disable-next-line no-console
    console.log("[generate-registry] no src/snaps/ found, wrote empty registry");
    return;
  }

  const entries = readdirSync(snapsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) => {
      const indexFile = join(snapsDir, name, "index.ts");
      return existsSync(indexFile);
    })
    .sort();

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-registry.ts. Do not edit by hand.",
    "// Re-run via `npm run generate` (or `npm run build` which calls it).",
    "",
    'import type { Hono } from "hono";',
    "",
  ];

  for (const name of entries) {
    const id = toIdentifier(name);
    lines.push(`import ${id} from "./snaps/${name}/index.js";`);
  }

  lines.push("");
  lines.push("export const snaps: Record<string, Hono> = {");
  for (const name of entries) {
    const id = toIdentifier(name);
    lines.push(`  ${JSON.stringify(name)}: ${id},`);
  }
  lines.push("};");
  lines.push("");

  writeFileSync(registryFile, lines.join("\n"));
  // eslint-disable-next-line no-console
  console.log(
    `[generate-registry] wrote ${entries.length} snap${entries.length === 1 ? "" : "s"}: ${entries.join(", ")}`,
  );
}

main();
