// AUTO-GENERATED by scripts/generate-registry.ts. Do not edit by hand.
// Re-run via `npm run generate` (or `npm run build` which calls it).

import type { Hono } from "hono";

import snap_creatureSummoner from "./snaps/creature-summoner/index.js";
import snap_doNotPress from "./snaps/do-not-press/index.js";
import snap_drumMachine from "./snaps/drum-machine/index.js";
import snap_energyReading from "./snaps/energy-reading/index.js";
import snap_followKayonfire from "./snaps/follow-kayonfire/index.js";
import snap_helloFarcaster from "./snaps/hello-farcaster/index.js";
import snap_loudLinks from "./snaps/loud-links/index.js";
import snap_meetSnapWizard from "./snaps/meet-snap-wizard/index.js";
import snap_mvrShowcase from "./snaps/mvr-showcase/index.js";
import snap_natalChart from "./snaps/natal-chart/index.js";
import snap_natalChartV2 from "./snaps/natal-chart-v2/index.js";
import snap_pacman from "./snaps/pacman/index.js";
import snap_snap101 from "./snaps/snap-101/index.js";
import snap_snapShowcase from "./snaps/snap-showcase/index.js";
import snap_snapathon from "./snaps/snapathon/index.js";
import snap_stumble from "./snaps/stumble/index.js";
import snap_vibeCheck from "./snaps/vibe-check/index.js";

export const snaps: Record<string, Hono> = {
  "creature-summoner": snap_creatureSummoner,
  "do-not-press": snap_doNotPress,
  "drum-machine": snap_drumMachine,
  "energy-reading": snap_energyReading,
  "follow-kayonfire": snap_followKayonfire,
  "hello-farcaster": snap_helloFarcaster,
  "loud-links": snap_loudLinks,
  "meet-snap-wizard": snap_meetSnapWizard,
  "mvr-showcase": snap_mvrShowcase,
  "natal-chart": snap_natalChart,
  "natal-chart-v2": snap_natalChartV2,
  "pacman": snap_pacman,
  "snap-101": snap_snap101,
  "snap-showcase": snap_snapShowcase,
  "snapathon": snap_snapathon,
  "stumble": snap_stumble,
  "vibe-check": snap_vibeCheck,
};
