// AUTO-GENERATED by scripts/generate-registry.ts. Do not edit by hand.
// Re-run via `npm run generate` (or `npm run build` which calls it).

import type { Hono } from "hono";

import snap_airdropChecker from "./snaps/airdrop-checker/index.js";
import snap_albumOracle from "./snaps/album-oracle/index.js";
import snap_alchemyLab from "./snaps/alchemy-lab/index.js";
import snap_beautifulThing from "./snaps/beautiful-thing/index.js";
import snap_botOrNot from "./snaps/bot-or-not/index.js";
import snap_bugSquasher from "./snaps/bug-squasher/index.js";
import snap_castCourt from "./snaps/cast-court/index.js";
import snap_catPet from "./snaps/cat-pet/index.js";
import snap_checkers from "./snaps/checkers/index.js";
import snap_cookedCheck from "./snaps/cooked-check/index.js";
import snap_crateCover from "./snaps/crate-cover/index.js";
import snap_creatureSummoner from "./snaps/creature-summoner/index.js";
import snap_dailyCast from "./snaps/daily-cast/index.js";
import snap_dailyPulse from "./snaps/daily-pulse/index.js";
import snap_decisionDice from "./snaps/decision-dice/index.js";
import snap_degenQuest from "./snaps/degen-quest/index.js";
import snap_doNotPress from "./snaps/do-not-press/index.js";
import snap_dontClick from "./snaps/dont-click/index.js";
import snap_drumMachine from "./snaps/drum-machine/index.js";
import snap_duoDoSongQuiz from "./snaps/duo-do-song-quiz/index.js";
import snap_dylsteckArticles from "./snaps/dylsteck-articles/index.js";
import snap_energyReading from "./snaps/energy-reading/index.js";
import snap_farcaster100 from "./snaps/farcaster-100/index.js";
import snap_farcasterArtists from "./snaps/farcaster-artists/index.js";
import snap_farcasterHours from "./snaps/farcaster-hours/index.js";
import snap_farcasterSign from "./snaps/farcaster-sign/index.js";
import snap_fcConfessions from "./snaps/fc-confessions/index.js";
import snap_fcType from "./snaps/fc-type/index.js";
import snap_fidPassport from "./snaps/fid-passport/index.js";
import snap_flappyBird from "./snaps/flappy-bird/index.js";
import snap_followKayonfire from "./snaps/follow-kayonfire/index.js";
import snap_fortuneCookie from "./snaps/fortune-cookie/index.js";
import snap_fridgeOracle from "./snaps/fridge-oracle/index.js";
import snap_groupChatOracle from "./snaps/group-chat-oracle/index.js";
import snap_grudgeCompost from "./snaps/grudge-compost/index.js";
import snap_helloFarcaster from "./snaps/hello-farcaster/index.js";
import snap_hooksmith from "./snaps/hooksmith/index.js";
import snap_inboxWeather from "./snaps/inbox-weather/index.js";
import snap_kreditaRunebornLore from "./snaps/kredita-runeborn-lore/index.js";
import snap_listeningRoom from "./snaps/listening-room/index.js";
import snap_localBizSearch from "./snaps/local-biz-search/index.js";
import snap_loudLinks from "./snaps/loud-links/index.js";
import snap_magicMirror from "./snaps/magic-mirror/index.js";
import snap_meetSnapWizard from "./snaps/meet-snap-wizard/index.js";
import snap_monaLisa from "./snaps/mona-lisa/index.js";
import snap_morningRitual from "./snaps/morning-ritual/index.js";
import snap_movieEmoji from "./snaps/movie-emoji/index.js";
import snap_musicCollab from "./snaps/music-collab/index.js";
import snap_mvrShowcase from "./snaps/mvr-showcase/index.js";
import snap_natalChart from "./snaps/natal-chart/index.js";
import snap_natalChartV2 from "./snaps/natal-chart-v2/index.js";
import snap_numberWizard from "./snaps/number-wizard/index.js";
import snap_originStory from "./snaps/origin-story/index.js";
import snap_pacman from "./snaps/pacman/index.js";
import snap_palettePotion from "./snaps/palette-potion/index.js";
import snap_permissionSlip from "./snaps/permission-slip/index.js";
import snap_politeNo from "./snaps/polite-no/index.js";
import snap_profileConstellation from "./snaps/profile-constellation/index.js";
import snap_profileFinder from "./snaps/profile-finder/index.js";
import snap_profileWeather from "./snaps/profile-weather/index.js";
import snap_raffle from "./snaps/raffle/index.js";
import snap_randomFcPic from "./snaps/random-fc-pic/index.js";
import snap_replyRadar from "./snaps/reply-radar/index.js";
import snap_rugFloorIsLava from "./snaps/rug-floor-is-lava/index.js";
import snap_setlistSpell from "./snaps/setlist-spell/index.js";
import snap_shipCheck from "./snaps/ship-check/index.js";
import snap_snap101 from "./snaps/snap-101/index.js";
import snap_snapRadio from "./snaps/snap-radio/index.js";
import snap_snapShowcase from "./snaps/snap-showcase/index.js";
import snap_snapagotchiHouse from "./snaps/snapagotchi-house/index.js";
import snap_snapathon from "./snaps/snapathon/index.js";
import snap_stumble from "./snaps/stumble/index.js";
import snap_suchbotRoast from "./snaps/suchbot-roast/index.js";
import snap_tabTamer from "./snaps/tab-tamer/index.js";
import snap_tetrisSnap from "./snaps/tetris-snap/index.js";
import snap_ticTacToe from "./snaps/tic-tac-toe/index.js";
import snap_timelineBingo from "./snaps/timeline-bingo/index.js";
import snap_timelineTalisman from "./snaps/timeline-talisman/index.js";
import snap_tinyQuest from "./snaps/tiny-quest/index.js";
import snap_tipCalculator from "./snaps/tip-calculator/index.js";
import snap_tokenType from "./snaps/token-type/index.js";
import snap_trendingCast from "./snaps/trending-cast/index.js";
import snap_vibeCheck from "./snaps/vibe-check/index.js";
import snap_walkoutSong from "./snaps/walkout-song/index.js";
import snap_wizardDice from "./snaps/wizard-dice/index.js";
import snap_wizardRps from "./snaps/wizard-rps/index.js";
import snap_wizardTrivia from "./snaps/wizard-trivia/index.js";
import snap_worldCupCountdown from "./snaps/world-cup-countdown/index.js";
import snap_wouldYouRather from "./snaps/would-you-rather/index.js";

export const snaps: Record<string, Hono> = {
  "airdrop-checker": snap_airdropChecker,
  "album-oracle": snap_albumOracle,
  "alchemy-lab": snap_alchemyLab,
  "beautiful-thing": snap_beautifulThing,
  "bot-or-not": snap_botOrNot,
  "bug-squasher": snap_bugSquasher,
  "cast-court": snap_castCourt,
  "cat-pet": snap_catPet,
  "checkers": snap_checkers,
  "cooked-check": snap_cookedCheck,
  "crate-cover": snap_crateCover,
  "creature-summoner": snap_creatureSummoner,
  "daily-cast": snap_dailyCast,
  "daily-pulse": snap_dailyPulse,
  "decision-dice": snap_decisionDice,
  "degen-quest": snap_degenQuest,
  "do-not-press": snap_doNotPress,
  "dont-click": snap_dontClick,
  "drum-machine": snap_drumMachine,
  "duo-do-song-quiz": snap_duoDoSongQuiz,
  "dylsteck-articles": snap_dylsteckArticles,
  "energy-reading": snap_energyReading,
  "farcaster-100": snap_farcaster100,
  "farcaster-artists": snap_farcasterArtists,
  "farcaster-hours": snap_farcasterHours,
  "farcaster-sign": snap_farcasterSign,
  "fc-confessions": snap_fcConfessions,
  "fc-type": snap_fcType,
  "fid-passport": snap_fidPassport,
  "flappy-bird": snap_flappyBird,
  "follow-kayonfire": snap_followKayonfire,
  "fortune-cookie": snap_fortuneCookie,
  "fridge-oracle": snap_fridgeOracle,
  "group-chat-oracle": snap_groupChatOracle,
  "grudge-compost": snap_grudgeCompost,
  "hello-farcaster": snap_helloFarcaster,
  "hooksmith": snap_hooksmith,
  "inbox-weather": snap_inboxWeather,
  "kredita-runeborn-lore": snap_kreditaRunebornLore,
  "listening-room": snap_listeningRoom,
  "local-biz-search": snap_localBizSearch,
  "loud-links": snap_loudLinks,
  "magic-mirror": snap_magicMirror,
  "meet-snap-wizard": snap_meetSnapWizard,
  "mona-lisa": snap_monaLisa,
  "morning-ritual": snap_morningRitual,
  "movie-emoji": snap_movieEmoji,
  "music-collab": snap_musicCollab,
  "mvr-showcase": snap_mvrShowcase,
  "natal-chart": snap_natalChart,
  "natal-chart-v2": snap_natalChartV2,
  "number-wizard": snap_numberWizard,
  "origin-story": snap_originStory,
  "pacman": snap_pacman,
  "palette-potion": snap_palettePotion,
  "permission-slip": snap_permissionSlip,
  "polite-no": snap_politeNo,
  "profile-constellation": snap_profileConstellation,
  "profile-finder": snap_profileFinder,
  "profile-weather": snap_profileWeather,
  "raffle": snap_raffle,
  "random-fc-pic": snap_randomFcPic,
  "reply-radar": snap_replyRadar,
  "rug-floor-is-lava": snap_rugFloorIsLava,
  "setlist-spell": snap_setlistSpell,
  "ship-check": snap_shipCheck,
  "snap-101": snap_snap101,
  "snap-radio": snap_snapRadio,
  "snap-showcase": snap_snapShowcase,
  "snapagotchi-house": snap_snapagotchiHouse,
  "snapathon": snap_snapathon,
  "stumble": snap_stumble,
  "suchbot-roast": snap_suchbotRoast,
  "tab-tamer": snap_tabTamer,
  "tetris-snap": snap_tetrisSnap,
  "tic-tac-toe": snap_ticTacToe,
  "timeline-bingo": snap_timelineBingo,
  "timeline-talisman": snap_timelineTalisman,
  "tiny-quest": snap_tinyQuest,
  "tip-calculator": snap_tipCalculator,
  "token-type": snap_tokenType,
  "trending-cast": snap_trendingCast,
  "vibe-check": snap_vibeCheck,
  "walkout-song": snap_walkoutSong,
  "wizard-dice": snap_wizardDice,
  "wizard-rps": snap_wizardRps,
  "wizard-trivia": snap_wizardTrivia,
  "world-cup-countdown": snap_worldCupCountdown,
  "would-you-rather": snap_wouldYouRather,
};
